#pragma once

#include "cli_args.h"
#include "execution_plan.h"
#include "frontend_ir.h"
#include "graph_ir.h"
#include "lexer.h"
#include "parser.h"
#include "semantic_analyzer.h"

#include <optional>
#include <string>
#include <variant>
#include <vector>

/**
 * @brief Represents the comprehensive result of compiling a program.
 * 
 * Contains the artifacts generated at each stage of the compiler pipeline, 
 * ranging from raw tokens and AST to lowered modules, execution plans, and 
 * optional string dumps used for debugging and diagnostics.
 */
struct CompiledProgram {
    /**
     * @brief Number of tokens generated by the lexer.
     * 1. Why it exists: Provides quick metrics without querying the vector size.
     * 2. What it tracks: The total count of valid tokens in the parsed source.
     * 3. What mutates/updates it: Mutated during the lexing phase (e.g., inside `compile_source`).
     */
    std::size_t token_count = 0;

    /**
     * @brief Collection of tokens produced by the lexer.
     * 1. Why it exists: Feeds the parser with a structured stream of tokens.
     * 2. What it tracks: The actual lexical tokens of the source file.
     * 3. What mutates/updates it: Updated during the lexing phase when reading source code.
     */
    std::vector<Token> tokens;

    /**
     * @brief The parsed Abstract Syntax Tree (AST) of the program.
     * 1. Why it exists: Acts as the structural representation of the source code for further analysis.
     * 2. What it tracks: The top-level program construct and all its hierarchical children.
     * 3. What mutates/updates it: Populated during the parsing phase.
     */
    Program program;

    /**
     * @brief Semantic information gathered from the AST.
     * 1. Why it exists: Enforces language rules, type checking, and symbol resolution.
     * 2. What it tracks: Types, symbol tables, and scoping data.
     * 3. What mutates/updates it: Populated during the semantic analysis phase.
     */
    SemanticInfo semantic_info;

    /**
     * @brief The intermediate representation (IR) of the program.
     * 1. Why it exists: Serves as a unified optimization and lowering target before backend generation.
     * 2. What it tracks: The lowered functions, blocks, and tensor operations.
     * 3. What mutates/updates it: Updated during the IR lowering phase.
     */
    LoweredModule lowered;

    /**
     * @brief The computational graph representation.
     * 1. Why it exists: Used for graph-based backends or high-level tensor optimizations.
     * 2. What it tracks: The directed acyclic graph of tensor operations.
     * 3. What mutates/updates it: Populated conditionally during the graph generation phase if requested or required by backend.
     */
    std::optional<GraphModule> graph;

    /**
     * @brief The finalized execution plan.
     * 1. Why it exists: Guides backend execution engines (e.g., Metal or local) on how to run the model.
     * 2. What it tracks: Memory allocations, kernel launches, and strict data dependencies.
     * 3. What mutates/updates it: Populated conditionally during the execution planning phase.
     */
    std::optional<PlanModule> plan;

    /**
     * @brief String representation of the token stream.
     * 1. Why it exists: Useful for debugging and diagnostic outputs.
     * 2. What it tracks: The formatted, dumped sequence of tokens.
     * 3. What mutates/updates it: Mutated when the `--tokens` CLI flag triggers a dump generation.
     */
    std::optional<std::string> token_dump;

    /**
     * @brief String representation of the Abstract Syntax Tree.
     * 1. Why it exists: Useful for debugging parser output and structural issues.
     * 2. What it tracks: The formatted AST structure.
     * 3. What mutates/updates it: Mutated when the `--ast` CLI flag triggers a dump generation.
     */
    std::optional<std::string> ast_dump;

    /**
     * @brief String representation of the semantic analysis results.
     * 1. Why it exists: Useful for debugging type checking and symbol resolution logic.
     * 2. What it tracks: The formatted semantic scopes and resolved types.
     * 3. What mutates/updates it: Mutated when the `--semantics` CLI flag triggers a dump generation.
     */
    std::optional<std::string> semantics_dump;

    /**
     * @brief String representation of the lowered IR.
     * 1. Why it exists: Useful for debugging the intermediate representation before backend generation.
     * 2. What it tracks: The formatted text of the lowered IR module.
     * 3. What mutates/updates it: Mutated when the `--ir` CLI flag triggers a dump generation.
     */
    std::optional<std::string> ir_dump;

    /**
     * @brief String representation of the computational graph.
     * 1. Why it exists: Useful for debugging graph structures and optimizations.
     * 2. What it tracks: The formatted text of the graph.
     * 3. What mutates/updates it: Mutated when the `--graph` CLI flag triggers a dump generation.
     */
    std::optional<std::string> graph_dump;

    /**
     * @brief String representation of the execution plan.
     * 1. Why it exists: Useful for debugging backend execution sequences and allocations.
     * 2. What it tracks: The formatted execution plan details.
     * 3. What mutates/updates it: Mutated when the `--plan` CLI flag triggers a dump generation.
     */
    std::optional<std::string> plan_dump;
};

using CompileResult = std::variant<CompiledProgram, Diagnostic>;

/**
 * @brief Drives the end-to-end compilation process for a given source string.
 *
 * Runs the source through the lexer, parser, semantic analyzer, and lowerers
 * to produce execution plans and graphs based on the requested CLI options.
 *
 * @param source The input program source code.
 * @param options CLI options controlling pipeline behavior and dumps.
 * @return CompileResult The populated CompiledProgram on success, or a Diagnostic error.
 */
CompileResult compile_source(const std::string& source, const CliOptions& options);

/**
 * @brief Prints an initial summary of the compilation inputs and options.
 *
 * @param options The user-provided CLI options.
 * @param source_size The size of the input source file in bytes.
 */
void print_bootstrap_summary(const CliOptions& options, std::size_t source_size);

/**
 * @brief Prints quantitative and structural metrics of the compiled program.
 *
 * Displays counts of tokens, layers, functions, and optionally IR node statistics.
 *
 * @param compiled The fully populated CompiledProgram.
 */
void print_compile_summary(const CompiledProgram& compiled);

/**
 * @brief Prints any requested diagnostic dumps (AST, IR, Execution Plan, etc.) to standard output.
 *
 * @param compiled The CompiledProgram containing the optional string dumps.
 */
void print_requested_dumps(const CompiledProgram& compiled);
